### ISSUE TITLE
Error: the fixed layout requires the slimscroll plugin!

### ISSUE THREAD

**Issue by duyetvn** [nicolas-besnard/adminlte2-rails#14]
I'm trying this gem but I meet this notification at console of web-browser
![screenshot from 2016-08-09 14 53 44](https://cloud.githubusercontent.com/assets/11748904/17510382/d72522f2-5e48-11e6-83e8-38605af1623e.png)

Please help me.
Thanks

**Comment by nicolas-besnard** [comment]
The answer is on the message :)

This is not really an error has everything is still working

**Comment by duyetvn** [comment]
thank you  for your answer.
I close this issue
