### ISSUE TITLE
rails generate admin_lte2 not working.

### ISSUE THREAD

**Issue by ryancsf** [nicolas-besnard/adminlte2-rails#2]
Hi Nicolas,

Before I start elaborating on the issue, I just wanted to say a BIG THANK YOU for developing this gem. You're literally my lifesaver. I was having difficulty integrating adminlte with my latest rails project and stumble upon your gem by accident, and it was the best accident ever. Thank you so much.

Now, for the issue, when I tried rails generate admin_lte2, it does not work, the same goes to rails generate admin_lte2_plugins, upon further trial and error, I discovered that rails generate admin_lte and rails generate admin_lte_plugin PLUGIN_NAME are the commands that worked for me. 

No big issues, but just thought you might want to update that in your readme file so that more people know about it :) 

Thank you so much for doing this and keep up the good works. Kudos!

Cheers,
Ryan

**Comment by nicolas-besnard** [comment]
Hi,

Thanks for your kind word :) The README is for the version 0.0.3 who is
coming tomorrow ! For now, you've to use `rails generate admin_lte` or `rails
generate admin_lte_plugins` to make it work !

**Comment by nicolas-besnard** [comment]
Hi,

Thanks for your kind word :) The README is for the version 0.0.3 who is
coming tomorrow ! I unfortunately doesn't have the time to do it today :( 

For now, you've to use `rails generate admin_lte` then `rails
generate admin_lte_plugins` to make it work !

**Comment by nicolas-besnard** [comment]
The version 0.0.3 is up !

**Comment by ryancsf** [comment]
Got it! Thanks :+1:
