### ISSUE TITLE
Links on the side-bar navigation do not stay 'active'

### ISSUE THREAD

**Issue by wung-s** [nicolas-besnard/adminlte2-rails#6]
Aren't the navigation links in the sidebar suppose to be in the 'active' state for whichever navigation link was clicked ? Sorry if there's an obvious thing that I am missing out, but I can't seem to get it to switch/remain in the 'active' state .. 
Btw, I changed nothing from what comes out-of-the-box with this gem. Your help would be much appreciated. 
![ex](https://cloud.githubusercontent.com/assets/5159585/9230209/9529ef18-413e-11e5-9dab-699b0344d318.png)

**Comment by nicolas-besnard** [comment]
The active class is not working out-of-the-box. I'm personnaly using [active_link_to](https://github.com/comfy/active_link_to) :)
