### ISSUE TITLE
Plugin generator not working for iCheck

### ISSUE THREAD

**Issue by ssldhl** [nicolas-besnard/adminlte2-rails#7]
While running the command: `rails g admin_lte2_plugins icheck`

Error appears:

> Could not find "iCheck/iCheck.js" in any of your source paths.

This is because, the generator is looking for `iCheck.js` but there is `icheck.js` present.

**Comment by nicolas-besnard** [comment]
@sushilthe Sorry for the delay. I think it was a bad idea to create a generator for each plugins as it's impossible to get the last version for each plugins.

Well, it's possible but it'll take a lot of time.
